version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
